### ISSUE TITLE
Excellent job!

### ISSUE THREAD

**Issue by tabacitu** [soufiene-slimi/star-field-for-backpack#1]
@soufiene-slimi , I just wanted to say that I needed this today and you saved my a$$. Thanks a lot! 

I've done a bad job of promoting add-ons in the past but this is all going to change. This add-on is now on our website and I'll start promoting it to our user base. I think everybody that needs this will love it - you've done a wonderful job. It's rare that I have zero comments - for this field - I really do have zero comments.

Cheers! 🥳 🎉

**Comment by soufiene-slimi** [comment]
Good to hear that from you 😁

**Comment by soufiene-slimi** [comment]
Good to hear that from you 😁
